spring.application.name=HealthCare

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/health_care_db
spring.datasource.username=root
spring.datasource.password=20010521
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect